title: xinika
author: xin liu 
subtitle: mumbling

url: "https://xxxxxxxxxinliu.github.io"
baseurl: "/blog"

footer_only_homepage: true
footer_url: "https://xxxxxxxxxinliu.com"
footer_text: "All views my own. Theme by pro-panda"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "My work site"
   absolute-link: "https://xxxxxxxxxinliu.com"
