---
layout: post
title: "Black Donut - A thought experiment"
subtitle: A collective project for Summa Technologica 
---

In the moment we encounter the black box, our point of view is predetermined. There are several possibilities:
1. We are outside the black box (as far as we know) and the box is an independent entity of which the edges are also visible. This is the most classic relationship of the observer and the blackbox, as in the Schrödinger’s cat experiment. We establish an almost confrontational relationship and the observer’s choices is “independent” of the status of the black box. The sense of otherness dominates our sense and assumptions. 
 
2. We are inside the black box. I have wondered about this possibility. But if so, the blackbox is the world itself, or at least our world. A close example could be our daily experience in social media algorithms: we are the product. Thus instead of confrontation, we might feel more frustration or powerlessness. The fact we are inside renders any of our actions an input, thus produces. 
 
3. We are outside of the black but we cannot see the edges. In this situation, our position is of question, as we cannot fully understand the shape of the box. Here I propose two possibilities in one shape: Black Donut.
 
 
Here, from the observer’s point of view, they cannot tell whether they are inside or outside of the donut.
 
Thus, the question is: Where are we?

Imagine we are inside the black box, which, let us also assume, does not permit any form of activity or knowledge, then life inside the black box is an illusion. If we are outside the black box, the situation is quite different: there is fullness of action and energy in it. To this extent, life is a taken for-granted fact outside the black box, in that it does not constitute, say, an epistemic barrier. It does not posit a ‘difference’. Conversely, life inside the black box reverses its constitution from where it is once inside it. The black box will have to allow for the skeptic’s curiosity, wonder, and science; it has to allow for difference, so to speak. Here the black box requires testing, experimentation, or the labor of the negative (in Hegelian terms). Life outside the black box is such that, where the fullness of life is ironically monotonous, human flourishing is reliant on inactivity or the absence of the will to know. Plato’s notion of the city of sows in the Republic comes to mind. Inside the black box is where Plato would find the city of speech or kallipolis, the city that labors and produces science and knowledge. Or rather, a city in which, where life is an imposing illusion, love or eros becomes a passionate test of reality, the passion for pursuing an object or a goal, or the truth behind the veil of appearances. I think we can connect this to Lem’s intellectronics,  the cybernetic complement of Plato’s love of wisdom. It is wisdom that is based on as much uncertainty as knowing certainty. Thus, the paradox of the black box enables us to think of pedagogy as an unironic form of living in and through the black box. It is unironic in the sense that life, or learning how to live, is only possible inside the black box. 

The next question is: how to construct/build a Black Box?. We believe the goal of this task would be, in a certain way, to build something that would function as an autonomous regulator of autonomy itself, from scratch. To envision a device that, in virtue of its material constitution and wiring, is capable of transforming its own algorithm as new inputs are received. Therefore, even if it might be impossible to render intelligible the steps that the device took in order to return an output, this hardly matters because its algorithm is constantly changing in virtue of its own constitutional autonomy. In the case of machine-learning, this outcome is generally a prediction function. In the case of the Black Box it might be the disruption of behavioral triggers oriented towards a false idea of equilibrium and value, creating the illusion of an actual homeostasis while precluding the possibility to replace the framework we use in order to render these concepts intelligible and less responsive to an essentialist perspective. An AGI is a black box, its capacity to learn, interact, and be an active member of any kind of community is provided by its material constitution.

Our aim in constructing a Black Box is to deploy the means for increasing the number of connections and frameworks available both to artistic practices and to the modes of organizations of a community. An appropriate conception of homeostasis in that case would stand for the maintenance of formal plurality, something that perhaps coincides with Lem’s idea of an Intelligence Amplifier. That said, what kind of homeostasis are we to attain? Homeostasis is empirically perceived on a global scale as the capitalist management of crisis. It is due to the entrenchment and inflation of one specific conception of value and equilibrium. Both are not concepts that should be contaminated with something like an underlying content or substantivity. “Value” and “Equilibrium” as concepts and ideals should be purged of their ideological content. However, the concept of ‘goal-oriented’ can be misleading, if our aim is to build a regulator of regulators, since maybe we cannot describe the goal of such types of devices in terms of content. Rather, such a goal is a certain kind of fidelity to the fact that new forms of structuring experience and what we call reality are always possible due to the very implications of the concept of autonomy. The example of a black box provided in our first class was the new AI technology called GPT-3. But we can also think about the whole functioning of machine learning as a black box. In fact, if we look carefully, learning as a device is itself a black box. It is not sufficient to have an adequate grasping of the neural processes we undergo when we learn. But as far as we are concerned with learning itself, as we commonly use the verb "to learn", even if we are aware of the functioning of our brain, learning is a black box. 

Black Donut is first of all a thought experiment. We tried to imagine what it would be like to give shape and contours to a black box as an object, taking Stanislaw Lem’s Summa Technologicae as a point of departure, more precisely the chapter  ‘Intellectronics’. The output of this experiment is a philosophical fiction that takes form as a video-art based on the story generated by a machine-learning technology. Here, we use AI Dungeon, a text adventure game that uses GPT-3 to generate content. We are turning the game into a process of learning. It is worth noting that the use of the gtp-3 technology in the AI Dungeon game is restrained in a way as to produce adventure stories or narrations. However, instead of rejecting it due to its constrained structure, this very delimitation is what makes us pursue ways of tinkering with its boundaries. We are interested in revealing the material contingency and technical consistency of its intelligence. This philosophical fiction is presented as a video whose script is organized around Lem’s futurological speculations about the Black Box as an homeostatic regulator.


